██████═╗ ██████╗ ██╗   ██╗██╗████████╗
██╔══██╝ ██╔══██╗██║   ██║██║╚══██╔══╝
██████╗  ██████╔╝██║   ██║██║   ██║   
██╔══██╗ ██╔══██╗██║   ██║██║   ██║   
██████╔╝ ██║  ██║╚██████╔╝██║   ██║   
╚═════╝  ╚═╝  ╚═╝ ╚═════╝ ╚═╝   ╚═╝   

   Bioacoustic Recognition of
  Unhealthy and Intact Tones


####### Preprocessing ######





