# ██████═╗ ██████╗ ██╗   ██╗██╗████████╗
# ██╔══██╝ ██╔══██╗██║   ██║██║╚══██╔══╝
# ██████╗  ██████╔╝██║   ██║██║   ██║   
# ██╔══██╗ ██╔══██╗██║   ██║██║   ██║   
# ██████╔╝ ██║  ██║╚██████╔╝██║   ██║   
# ╚═════╝  ╚═╝  ╚═╝ ╚═════╝ ╚═╝   ╚═╝   

# Bioacoustic Recognition of Unhealthy and Intact Tones


####### Preprocessing ######

preprocessing:

  sample_rate: 16000
  mono: true
  normalize: true

  filter:
    enabled: true
    lowcut: 200
    highcut: 1200
    adaptive_lowcut:
      enabled: True
      order: 5
      adaptive_lowcut_range: [20, 250]
      highcut: 1200
      steps: 10
      peak_prominence: 0.05
      plot_debug: True
    

  splitting:
    enabled: true
    min_spacing: 0.3
    max_spacing: 0.6
    context: 0.1
    peak_prominence: 0.05
    rms_window: 0.1
    rms_peak_prominence: 0.005

  save_full_filtered_waveform: false
  save_segment_waveform: true




####### Model Training ######
model_training:
  classifier: true
  model_path: "models/"

####### Plotting ######
plotting:
  save_preprocessed_plots: true
  save_spectogram_plots: true
  plot: true